// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using priceNegotiationAPI.Data;

#nullable disable

namespace priceNegotiationAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231207161138_initial-values-date")]
    partial class initialvaluesdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("priceNegotiationAPI.Models.Negotiation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Accepted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ProposedPrice")
                        .HasColumnType("REAL");

                    b.Property<bool>("WasHandled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Negotiations");
                });

            modelBuilder.Entity("priceNegotiationAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 7, 17, 11, 38, 551, DateTimeKind.Local).AddTicks(101),
                            Description = "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
                            Name = "Fight Club",
                            Price = 25.989999999999998
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 12, 7, 17, 11, 38, 551, DateTimeKind.Local).AddTicks(135),
                            Description = "The drug-induced utopias of four Coney Island people are shattered when their addictions run deep.",
                            Name = "Requiem for a Dream",
                            Price = 17.989999999999998
                        });
                });

            modelBuilder.Entity("priceNegotiationAPI.Models.Negotiation", b =>
                {
                    b.HasOne("priceNegotiationAPI.Models.Product", "Product")
                        .WithMany("Negotiations")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("priceNegotiationAPI.Models.Product", b =>
                {
                    b.Navigation("Negotiations");
                });
#pragma warning restore 612, 618
        }
    }
}
